Added Usage
Added Usage.

diff --git a/postgres/backup_test b/postgres/backup_test
--- a/postgres/backup_test
+++ b/postgres/backup_test
@@ -18,7 +18,38 @@
 
 #Syntax: backup_test [optional switches] backupfilename
 
+
+#Functions
 #TODO Usage
+usage() {
+  echo "Usage: $PROG [options] <filename>"
+  echo " -a --all : All file and folders in the current folder.( $(pwd) )"
+  echo " -h --help : Print this Message."
+}
+
+#Varriables
+all_flag=0
+
+#while loop for Usage
+while getopts ":a:h:" opt;
+do
+  case $opt in
+    a)
+      sys_ram=$OPTARG;
+      ;;
+    h)
+      usage;
+      exit 1;
+      ;;
+    \?)
+      echo "Invalid option -$opt" >&2
+      usage;
+      exit 1;
+      ;;
+  esac
+done
+
+
 #TODO Test usage
 #TODO Pull information from backup.conf
 #TODO Test Pull from backup.conf
